### ISSUE TITLE
Doesn't work on Firefox

### ISSUE THREAD

**Issue by iangilman** [harshalitalele/OpenSeadragonDraggableNavigator#1]
I've tried your demo on Mac Chrome and Firefox. It works on Chrome but not on Firefox. I haven't tried Safari or Edge.

On Firefox when I try to drag the little plus icon it just doesn't move.

**Comment by harshalitalele** [comment]
Yep, I saw that now. There's this issue in firefox in dragging elements like div and buttons.
So, I have used an SVG icon instead and it seems it is working in Chrome, Edge, and Firefox now.
Couldn't check it in Safari. Will check there too.

**Comment by iangilman** [comment]
Indeed, it now works in Firefox! One odd thing is that the navigator disappears during the drag (unlike on other browsers).

I've also verified that it works in Safari (without the disappearing issue).

**Comment by harshalitalele** [comment]
Yes, even I observed that thing but wasn't sure what must be causing it.

There's a slight difference between 'drag' and 'dragover' events that I ignored. 
I was preventing default dragover functionality, which didn't matter to other browsers, but in Firefox probably that occurs after drag event which made the difference.

I have made changes for this! 

Thanks! :)

**Comment by iangilman** [comment]
Lovely... looking good on Firefox!
